# Site settings
title: MunkiReport Docs
email: your-email@domain.com
description: >
  MunkiReport-PHP Documentation

baseurl: "/munkireport-docs/" # the subpath of your site, e.g. /blog/
url: https://wardsparadox.github.io/munkireport-docs/ # the base hostname & protocol for your site
git_address: https://github.com/wardsparadox/munkireport-docs
git_edit_address: https://github.com/munkireport/munkireport-php

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: yeti

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Denver
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
